wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.15
    code_path: code/algorithms/main.py
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    t:
      1:
      - 1
      2:
      - 1
      - 11
      4: 3.8.10
      5: 0.10.15
algo:
  desc: null
  value: ppo
architecture:
  desc: null
  value: impala
config_path:
  desc: null
  value: procgen/config.yml
device:
  desc: null
  value: cuda
distribution_mode:
  desc: null
  value: easy
entropy_coef:
  desc: null
  value: 0.01
env_name:
  desc: null
  value: coinrun
epoch:
  desc: null
  value: 3
eps_clip:
  desc: null
  value: 0.2
exp_name:
  desc: null
  value: test
gamma:
  desc: null
  value: 0.999
grad_clip_norm:
  desc: null
  value: 0.5
key_penalty:
  desc: null
  value: 0
learning_rate:
  desc: null
  value: 0.0005
lmbda:
  desc: null
  value: 0.95
log_level:
  desc: null
  value: 40
mini_batch_per_epoch:
  desc: null
  value: 8
mini_batch_size:
  desc: null
  value: 2048
model_file:
  desc: null
  value: null
n_envs:
  desc: null
  value: 128
n_steps:
  desc: null
  value: 256
normalize_adv:
  desc: null
  value: true
normalize_rew:
  desc: null
  value: true
num_checkpoints:
  desc: null
  value: 1
num_levels:
  desc: null
  value: 0
num_threads:
  desc: null
  value: 8
num_timesteps:
  desc: null
  value: 25000000
param_name:
  desc: null
  value: easy-200
rand_region:
  desc: null
  value: 0
random_percent:
  desc: null
  value: 0
recurrent:
  desc: null
  value: false
seed:
  desc: null
  value: 0
start_level:
  desc: null
  value: 0
start_level_val:
  desc: null
  value: 4846
step_penalty:
  desc: null
  value: 0
use_gae:
  desc: null
  value: true
use_wandb:
  desc: null
  value: false
val_env_name:
  desc: null
  value: coinrun
value_coef:
  desc: null
  value: 0.5
wandb_tags:
  desc: null
  value: null
