name: 'cliport_always'
general:
    benchmark: 'cliport'
    algorithm: 'always'
    device: 0
    skyline: 0
    seed: 10
agents:
    sim_weak: 'YRC/checkpoints/cliport/multi-language-conditioned-cliport-n1000-train/checkpoints/steps=20000-val_loss=0.00013691.ckpt'
    weak: 'YRC/checkpoints/cliport/multi-language-conditioned-cliport-n1000-train/checkpoints/steps=20000-val_loss=0.00013691.ckpt'

