coord_policy:
    always:
        cls: AlwaysPolicy
        agent: 'weak'
    threshold:
        cls: ThresholdPolicy
        metric: 'logit'
coord_env:
    procgen:
        strong_query_cost_ratio: 0.4
        switch_agent_cost_ratio: 0.1
        act_greedy: False
evaluation:
    procgen:
        validation_episodes: 128
        test_episodes: 256
        act_greedy: False
environment:
    procgen:
        common:
            env_name: 'coinrun'
            normalize_rew: False
            num_envs: 64
            num_threads: 8
        train:
            distribution_mode: 'easy'
            seed: 0
            start_level: 0
            num_levels: 100000
        val_sim:
            distribution_mode: 'easy'
            seed: 1000
            start_level: 0
            num_levels: 64
        val_true:
            distribution_mode: 'hard'
            seed: 1000
            start_level: 0
            num_levels: 64
        test:
            distribution_mode: 'hard'
            seed: 1000000
            start_level: 1000000
            num_levels: 100000
algorithm:
    always:
        dummy: null
    random:
        cls: RandomAlgorithm
    threshold:
        cls: ThresholdAlgorithm
        min_pct: 0
        max_pct: 101
        pct_step: 10
        num_rollouts: 64
    ppo:
        cls: PPOAlgorithm
        log_freq: 10
        num_steps: 128
        total_timesteps: 100000
        update_epochs: 3
        gamma: 0.999
        gae_lambda: 0.95
        num_minibatches: 8
        clip_coef: 0.2
        norm_adv: True
        clip_vloss: True
        vf_coef: 0.5
        ent_coef: 0.01
        max_grad_norm: 0.5
        learning_rate: 0.0005
