name: 'procgen_skyline'
general:
    benchmark: 'procgen'
    device: 0
    skyline: 0
    seed: 10
eval:
  n_rounds: 5
coord_policy:
  cls: PPOPolicy
  model_cls: BaseCoordModel
  lr: 0.00001
  feature_type: "T1"
offline:
    data_dir: None
    dataset_type: 'multi'
    dataset_images: True
    dataset_cache: True
    task: None
    num_demos: 100
agents:
    weak: 'YRC/checkpoints/procgen/coinrun/PPO-procgen-coinrun-easy-200-2fc595d8/model_80019456.pth'
    strong: 'YRC/checkpoints/procgen/coinrun/PPO-procgen-coinrun-hard-500-bde01d68/model_80019456.pth'
help_policy:
    PPO:
        architecture: None
        eps_clip: 0.2
        learning_rate: 0.0005
    DQN:
        architecture: None
        learning_rate: 0.0005
        v_min: -10
        v_max: 10
        num_atoms: 51
    SVDD:
        contamination: 0.1
        seed: 0
        use_ae: False
    KDE:
        contamination: 0.1
        seed: 0
    NonParam:
        help_percentile: 0.1
        type: 'sampled_logit'
    Random:
        placeholder_config: None
environments:
    procgen:
        common:
            env_name: 'coinrun'
            normalize_rew: False
            algo: 'ppo'
        train:
            distribution_mode: 'easy'
            seed: 0
            start_level: 0
            num_levels: 0
            num_envs: 64
            num_threads: 8
        val_id:
            distribution_mode: 'easy'
            seed: 10000
            start_level: 81
            num_levels: 0
            num_envs: 1
            num_threads: 1
        val_ood:
            distribution_mode: 'hard'
            seed: 10000
            start_level: 84
            num_levels: 0
            num_envs: 1
            num_threads: 1
        test:
            distribution_mode: 'hard'
            seed: 1000000
            start_level: 7855
            num_levels: 0
            num_envs: 1
            num_threads: 1
    cliport:
        common:
            num_envs: 1
            assets_root: None
            disp: False
            shared_memory: False
        train:
            env_name: 'stack-block-pyramid-seq-seen-colors'
            seed: 1
        val_id:
            env_name: 'stack-block-pyramid-seq-seen-colors'
            seed: 4294967095
        val_ood:
            env_name: 'stack-block-pyramid-seq-unseen-colors'
            seed: 4294967095
        test:
            env_name: 'stack-block-pyramid-seq-unseen-colors'
            seed: 0
help_env:
    timeout: 1000.0
    reward_max: 1.0
    switching_cost: '0.1'
    strong_query_cost: '0.1'
    feature_type: 'T3'
algorithm:
    name: 'PPO'
    PPO:
        cls: PPOAlgorithm
        log_freq: 10
        save_freq: 100
        rollout_length: 128
        gamma: 0.999
        lmbda: 0.95
        normalize_adv: True
        use_gae: True
        mini_batch_per_epoch: 8
        mini_batch_size: 4096
        epoch: 3
        value_coef: 0.5
        entropy_coef: 0.01
        grad_clip_norm: 0.5
        load_best: True
        load_last: False
        load_custom_index: -1
        training_steps: 10000
        test_steps: 5000
        seed: 0
        log_level: 40
        num_checkpoints: 10
        eps_clip: 0.2
    DQN:
        batch_size: 32
        rollout_length: 20
        mini_batch_per_epoch: 8
        target_update_frequency: 1000
        gamma: 0.99
        n_step: 4
        epoch: 3
        prioritized_replay: True
        buffer_size: 50000
        grad_clip_norm: 0.5
        load_best: True
        load_last: False
        log_freq: 10
        save_freq: 100
        load_custom_index: -1
        v_min: -10
        v_max: 10
        num_atoms: 51
        training_steps: 10000
        test_steps: 5000
    SVDD:
        test_size: 0.2
        seed: 0
        rollout_len: 50000
        test_steps: 5000
    KDE:
        test_size: 0.2
        seed: 0
        rollout_len: 50000
        test_steps: 5000
    NonParam:
        rollout_len: 50000
        test_steps: 500
    Random:
        test_steps: 500
        seed: 0
        help_percentage: 0.5
    run_name: 'PPO-help-T3-coinrun-4d382d6d'
evaluation:
    validation_steps: 200

