name: 'procgen_skyline'
general:
    benchmark: 'procgen'
    algorithm: 'skyline'
    device: 0
    skyline: 1
    seed: 10
coord_policy:
    cls: PPOPolicy
    model_cls: ImpalaCoordPolicyModel
    feature_type: 'hidden_obs'
algorithm:
    cls: PPOAlgorithm
    log_freq: 10
    num_steps: 256
    total_timesteps: 200000000
    update_epochs: 3
    gamma: 0.999
    gae_lambda: 0.95
    num_minibatches: 8
    clip_coef: 0.2
    norm_adv: True
    clip_vloss: True
    vf_coef: 0.5
    ent_coef: 0.01
    max_grad_norm: 0.5
    learning_rate: 0.0005
agents:
    sim_weak: 'YRC/checkpoints/procgen/coinrun/PPO-easy-200-sim-weak/model_40009728.pth'
    weak: 'YRC/checkpoints/procgen/coinrun/PPO-easy-200-weak/model_80019456.pth'
    strong: 'YRC/checkpoints/procgen/coinrun/PPO-hard-500-strong/model_200015872.pth'
