name: 'procgen_always'
general:
    benchmark: 'procgen'
    algorithm: 'always'
    device: 0
    skyline: 0
    seed: 10
agents:
    sim_weak: 'YRC/checkpoints/procgen/coinrun/PPO-easy-200-sim-weak/model_40009728.pth'
    weak: 'YRC/checkpoints/procgen/coinrun/PPO-easy-200-weak/model_80019456.pth'
    strong: 'YRC/checkpoints/procgen/coinrun/PPO-hard-500-strong/model_200015872.pth'


