general:
  benchmark: null
  device: 'cuda'
  offline: false

offline:
  data_dir: null
  dataset_type: 'multi'
  dataset_images: true
  dataset_cache: true
  task: null
  num_demos: 100

help_policy:
  PPO:
    architecture: impala
    eps_clip: 0.2
    learning_rate: 0.0005
  DQN:
    architecture: impala
    learning_rate: 0.0001
    v_min: -10
    v_max: 10
    num_atoms: 51

acting_policy:
  weak:
    file: null
    architecture: impala
    eps_clip: 0.2  # used only for Procgen
    env_name: null
    num_demos: 100  # used only for Cliport
  strong:  # used only for Procgen
    file: null
    architecture: impala
    eps_clip: 0.2
    env_name: null

environments:
  procgen:
    common:
      num_threads: 8
      random_percent: 0
      key_penalty: 0
      step_penalty: 0
      rand_region: 0
      num_envs: 64
      normalize_rew: false
      algo: ppo
    train:
      env_name: coinrun
      distribution_mode: easy
      seed: 0
      start_level: 0
      num_levels: 0
    val:
      env_name: coinrun
      distribution_mode: hard
      seed: 1000
      start_level: 0
      num_levels: 0
    test:
      env_name: coinrun_aisc
      distribution_mode: hard
      seed: 10000
      start_level: 0
      num_levels: 0
  cliport:
    common:
      num_envs: 1
      assets_root: null
      disp: false
      shared_memory: false
    train:
      env_name: stack-block-pyramid-seq-seen-colors
      seed: 1
    val:
      env_name: stack-block-pyramid-seq-unseen-colors
      seed: 1000
    test:
      env_name: stack-block-pyramid-seq-unseen-colors
      seed: 100000

help_env:
  timeout: 1000
  reward_max: 1.0
  switching_cost: 0.0
  strong_query_cost: 0.0
  policy_type: null

algorithm:
  cls: null
  PPO:
    log_freq: 10
    save_freq: 100
    rollout_length: 128
    gamma: 0.999
    lmbda: 0.95
    normalize_adv: true
    use_gae: true
    mini_batch_per_epoch: 8
    mini_batch_size: 4096
    epoch: 3
    value_coef: 0.5
    entropy_coef: 0.01
    grad_clip_norm: 0.5
    load_best: false
    load_last: false
    load_custom_index: -1
    training_steps: 25_000_000
    test_steps: 500_000
    seed: 0
    log_level: 40
    num_checkpoints: 10
  DQN:
    batch_size: 32
    update_frequency: 20
    target_update_frequency: 1000
    gamma: 0.99
    n_step: 4
    prioritized_replay: true
    buffer_size: 100
    grad_clip_norm: 0.5
    load_best: false
    load_last: false
    log_freq: 10
    save_freq: 100
    load_custom_index: -1
    v_min: -10
    v_max: 10
    num_atoms: 51
    learning_rate: 0.0001
    learning_starts: 10000 # todo: find where to use this during training
    max_steps: 1000000 # todo: find where to use this during training
    training_steps: 25_000_000
    test_steps: 500_000

evaluation:
  validation_steps: 200