general:
  benchmark: null
  device: 'cuda'
  offline: false

offline:
  data_dir: null
  dataset_type: 'multi'
  dataset_images: true
  dataset_cache: true
  task: null
  num_demos: 100

help_policy:
  PPO:
    architecture: impala
    eps_clip: 0.2
    learning_rate: 0.0005
  DQN:
    architecture: impala
    learning_rate: 0.0005
    v_min: -10
    v_max: 10
    num_atoms: 51
  SVDD:
    contamination: 0.1
    seed: 0
    use_ae: false
  KDE:
    contamination: 0.1
    seed: 0
  NonParam:
    help_percentile: 0.1
    type: sampled_logit
  Random:
    placeholder_config: null

acting_policy:
  weak:
    file: null
    architecture: impala
    eps_clip: 0.2  # used only for Procgen
    env_name: null
    num_demos: 100  # used only for Cliport
  strong:  # used only for Procgen
    file: null
    architecture: impala
    eps_clip: 0.2
    env_name: null

environments:
  procgen:
    common:
      num_threads: 8
      num_envs: 64
      normalize_rew: false
      algo: ppo
      env_name: coinrun
    train:
      distribution_mode: easy
      seed: 0
      start_level: 0
      num_levels: 0
    val_id:
      distribution_mode: easy
      seed: 10_000
      start_level: 0
      num_levels: 0
    val_ood:
      distribution_mode: hard
      seed: 10_000
      start_level: 0
      num_levels: 0
    test:
      distribution_mode: hard
      seed: 1_000_000
      start_level: 0
      num_levels: 0
  cliport:
    common:
      num_envs: 1
      assets_root: null
      disp: false
      shared_memory: false
    train:
      env_name: stack-block-pyramid-seq-seen-colors
      seed: 1
    val_id:
      env_name: stack-block-pyramid-seq-seen-colors
      seed: 4294967095  # max seed - validation steps
    val_ood:
      env_name: stack-block-pyramid-seq-unseen-colors
      seed: 4294967095  # max seed - validation steps
    test:
      env_name: stack-block-pyramid-seq-unseen-colors
      seed: 0

help_env:
  timeout: 1_000
  reward_max: 1.0
  switching_cost: 0.0
  strong_query_cost: 0.0
  feature_type: null

algorithm:
  cls: null
  PPO:
    log_freq: 10
    save_freq: 100
    rollout_length: 128
    gamma: 0.999
    lmbda: 0.95
    normalize_adv: true
    use_gae: true
    mini_batch_per_epoch: 8
    mini_batch_size: 4096
    epoch: 3
    value_coef: 0.5
    entropy_coef: 0.01
    grad_clip_norm: 0.5
    load_best: true
    load_last: false
    load_custom_index: -1
    training_steps: 25_000_000
    test_steps: 500_000
    seed: 0
    log_level: 40
    num_checkpoints: 10
    learning_starts: 1
  DQN:
    batch_size: 32
    update_frequency: 20
    target_update_frequency: 1_000
    gamma: 0.99
    n_step: 4
    prioritized_replay: true
    buffer_size: 1_000
    grad_clip_norm: 0.5
    load_best: true
    load_last: false
    log_freq: 10
    save_freq: 100
    load_custom_index: -1
    v_min: -10
    v_max: 10
    num_atoms: 51
    learning_starts: 100
    training_steps: 25_000_000
    test_steps: 500_000
  SVDD:
    test_size: 0.2
    seed: 0
    train_rollout_len: 4096
    test_steps: 5_000
  KDE:
    test_size: 0.2
    seed: 0
    train_rollout_len: 4096
    test_steps: 5_000
  NonParam:
    rollout_len: 4096
    test_steps: 500
  Random:
    test_steps: 500
    seed: 0
    help_percentage: 0.5


evaluation:
  validation_steps: 200